name: CI/CD Deploy to VPS

on:
  workflow_dispatch:      # manual trigger
  push:                   # otomatis saat push ke main
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Prepare SSH key (robust base64 decode)
        shell: bash
        env:
          VPS_KEY_B64: ${{ secrets.VPS_KEY_B64 }}
        run: |
          set -euo pipefail
          # decode base64 (abaikan karakter non-base64 + bersihkan whitespace)
          printf "%s" "$VPS_KEY_B64" | tr -d '\r\n ' | base64 --decode --ignore-garbage > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          # sanity check: pastikan private key valid
          ssh-keygen -y -f /tmp/deploy_key >/dev/null 2>&1 || { echo "Private key invalid after decode"; exit 255; }

      - name: Test SSH connectivity (debug)
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "Testing SSH connectivity to $VPS_USER@$VPS_HOST"
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i /tmp/deploy_key $VPS_USER@$VPS_HOST 'echo SSH_OK' || (echo 'SSH test failed' && exit 1)
          echo 'SSH connectivity OK'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Clean dist di VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: /tmp/deploy_key
          # port: 22   # uncomment kalau pakai port custom, ganti angkanya
          script: |
            rm -rf /var/www/compro1/dist
            mkdir -p /var/www/compro1/dist

      - name: Upload dist ke VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: /tmp/deploy_key
          # port: 22   # samakan kalau SSH di port custom
          source: "dist/*"
          target: "/var/www/compro1/dist"
    