name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Test SSH connectivity (debug)
        if: always()
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_KEY: ${{ secrets.VPS_KEY }}
        run: |
          echo "Testing SSH connectivity to $VPS_USER@$VPS_HOST"
          # write key to a temp file and restrict permissions
          echo "$VPS_KEY" > /tmp/deploy_key && chmod 600 /tmp/deploy_key
          # try a simple command
          ssh -o StrictHostKeyChecking=no -i /tmp/deploy_key $VPS_USER@$VPS_HOST 'echo SSH_OK' || (echo 'SSH test failed' && exit 1)
          echo 'SSH connectivity OK'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Clean dist di VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            rm -rf /var/www/compro1/dist
            mkdir -p /var/www/compro1/dist

      - name: Upload dist ke VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/*"
          target: "/var/www/compro1/dist"
