name: CI/CD Build & Deploy (PROD - Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.VPS_KEY_B64 }}" | base64 -d > $GITHUB_WORKSPACE/deploy_key
          chmod 600 $GITHUB_WORKSPACE/deploy_key

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u fardilk --password-stdin

      - name: Build and Push Docker image to GHCR (prod)
        run: |
          IMAGE_NAME=ghcr.io/fardilk/excellenceplusweb:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to VPS via Docker (prod)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key_path: /github/workspace/deploy_key
          script: |
            docker login ghcr.io -u fardilk -p ${{ secrets.GHCR_PAT }}
            docker pull ghcr.io/fardilk/excellenceplusweb:latest
            docker stop excellenceplusweb || true
            docker rm excellenceplusweb || true
            docker run -d --name excellenceplusweb -p 80:80 ghcr.io/fardilk/excellenceplusweb:latest

